### ISSUE TITLE
Run with updated packages

### ISSUE THREAD

**Issue by tsbertalan** [lrjconan/RBP#2]
```bash
pyenv install 3.6.0
pyenv shell 3.6.0
python3.6 -m venv ~/.virtualenvs/rbp
source ~/.virtualenvs/rbp/bin/activate
wget https://download.pytorch.org/whl/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
# Select matching torchvision from https://pypi.org/project/torchvision/
wget https://download.pytorch.org/whl/torchvision-0.4.0+cpu-cp36-cp36m-manylinux1_x86_64.whl
pip install torch-0.4.0-cp36-cp36m-linux_x86_64.whl
pip install torchvision-0.4.0+cpu-cp36-cp36m-manylinux1_x86_64.whl
pip install numpy matplotlib cffi sklearn pyaml easydict
bash setup.sh
python run_exp.py -c config/hopfield.yaml
```

Gives
```
Traceback (most recent call last):
  File "run_exp.py", line 47, in <module>
    main()
  File "run_exp.py", line 15, in main
    config = get_config(args.config_file)
  File "/home/tsbertalan/Dropbox/Projects/RBP/utils/arg_helper.py", line 38, in get_config
    config = edict(yaml.load(open(config_file, "r")))
TypeError: load() missing 1 required positional argument: 'Loader'
```

Installing instead the oldest pyaml I can with my pip in this env (pyaml==12.12.5) gives the same.

```bash
(rbp) tsbertalan@pico:~/Dropbox/Projects/RBP$ pip freeze
cffi==1.15.0
cycler==0.11.0
easydict==1.9
joblib==1.1.0
kiwisolver==1.3.1
matplotlib==3.3.4
numpy==1.19.5
Pillow==8.4.0
pyaml==12.12.5
pycparser==2.21
pyparsing==3.0.7
python-dateutil==2.8.2
PyYAML==6.0
scikit-learn==0.24.2
scipy==1.5.4
six==1.16.0
sklearn==0.0
threadpoolctl==3.1.0
torch==0.4.0
torchvision==0.2.2
tqdm==4.19.9
You are using pip version 9.0.1, however version 22.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I know this code is somewhat old and probably a better approach is just to use it as a guide for a newer implementation, but would it be possible to at least provide a requirements.txt so I wouldn't waste time searching for and downloading incorrect old wheels? If not, I can update the pyaml usages later.

**Comment by lrjconan** [comment]
Thanks for your interest! Sorry that I do not have a requirements.txt for now.
You could bypass it by using `yaml.load(fo.read(), Loader=yaml.FullLoader)` or just install old pyyaml like 5.4.1 shown in [this link](https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col).
Meanwhile, you are welcome to submit a pull request once you work out a working requirements.txt.
